server:
  port: 7777

logging:
  level:
    root: INFO
    com.rw.random: DEBUG

spring:
  jackson:
    generator:
      write_numbers_as_strings: true
  security:
    strategy: MODE_GLOBAL
  redis:
    host: 127.0.0.1
    password:
    database: 0
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3307/random_world?useSSL=false&useUnicode=true&characterEncoding=utf-8&sslMode=disabled
    username: root
    password: Chiwen2233
    timeout: 10

random-world:
  security:
    authentication:
      jwt:
        secret: ODdiNDZjNTc2OTYyMzZiZTdlYzM0ZTZlYTM1YjczNzQ3ODhkMjBiNzM5NGZlMjUwMmJlOWRlMWYwNTQ3YzQyNWQxYWRiNDZkMzFkZmZhOGJiOTZjZmZlOWIxYWYxMWZkMzQzNDg4YTdkYjU4NDhhMDU4OGNlZjNlMDk4NzZmZmY=
  websocket:
    core-url: http://127.0.0.1:8080



