server:
  port: 7777

logging:
  level:
    root: INFO
    com.rw.random: DEBUG

spring:
  security:
    strategy: MODE_GLOBAL
  redis:
    host: 47.110.249.236
    password: Sunlight
    database: 0
  r2dbc:
    url: r2dbc:mysql://47.110.249.236:3306/random_world?useSSL=false&useUnicode=true&characterEncoding=utf-8&sslMode=disabled
    username: root
    password: Sunlight
    timeout: 10

random-world:
  security:
    authentication:
      jwt:
        secret: ODdiNDZjNTc2OTYyMzZiZTdlYzM0ZTZlYTM1YjczNzQ3ODhkMjBiNzM5NGZlMjUwMmJlOWRlMWYwNTQ3YzQyNWQxYWRiNDZkMzFkZmZhOGJiOTZjZmZlOWIxYWYxMWZkMzQzNDg4YTdkYjU4NDhhMDU4OGNlZjNlMDk4NzZmZmY=
  websocket:
    core-url: http://127.0.0.1:8080



