logging:
  level:
    root: INFO
    com.rw.random: INFO
spring:
  jackson:
    generator:
      write_numbers_as_strings: true
  redis:
    host: 47.110.249.236
    password:
    database: 0
  r2dbc:
    url: r2dbc:mysql://47.110.249.236:3306/random_world?useSSL=false&useUnicode=true&characterEncoding=utf-8&sslMode=disabled
    username: root
    password: rwfish74!
    timeout: 10


random-world:
  load-test-fish-count: 500
  personality-name:
    - 人参
    - 人发
    - 卜芥
    - 儿茶
    - 八角
    - 丁香
    - 刀豆
    - 三七
    - 三棱
    - 干姜
    - 干漆
    - 广白
    - 广角
    - 广丹
    - 大黄
    - 大戟
    - 大枣
    - 大蒜
    - 大蓟
    - 小蓟
    - 小麦
    - 小蘖
    - 山丹
    - 山茶
    - 山奈
    - 山香
    - 山枣
    - 山栀
    - 山姜
    - 山药
    - 山楂
    - 川羌
    - 川军
    - 川连
    - 川朴
    - 川乌
    - 川柏
    - 川谷
    - 川断
    - 川椒
    - 川贝
    - 川芎
    - 马兰
    - 马辛
    - 马菜
    - 马莲
    - 马宝
    - 马勃
    - 马蔺
    - 卫茅
    - 子苓
    - 天冬
    - 天虫
    - 天龙
    - 天雄
    - 天麻
    - 元胡
    - 元参
    - 木瓜
    - 木耳
    - 木莲
    - 木香
    - 木通
    - 木贼
    - 木豆
    - 木笔
    - 木蓝
    - 牙皂
    - 瓦松
    - 瓦韦
    - 贝子
    - 贝母
    - 贝齿
    - 牛至
    - 牛黄
    - 牛膝
    - 牛蒡
    - 见愁
    - 手参
    - 毛鸡
    - 毛茛
    - 毛姜
    - 升麻
    - 升登
    - 丹砂
    - 丹皮
    - 丹参
    - 乌茜
    - 乌韭
    - 乌药
    - 乌头
    - 乌桕
    - 乌梅
    - 方海
    - 六曲
    - 文元
    - 文蛤
    - 仁杞
    - 双花
    - 双皮
    - 水花
    - 水萍
    - 水韭
    - 水莽
    - 水蛭
    - 巴豆
    - 玉桂
    - 玉竹
    - 玉金
    - 甘松
    - 甘草
    - 甘遂
    - 艾叶
    - 艾片
    - 艾蒿
    - 石韦
    - 石耳
    - 石灰
    - 石斛
    - 石膏
    - 石榴
    - 石燕
    - 石竹
    - 石蜜
    - 龙胆
    - 龙齿
    - 龙骨
    - 龙葵
    - 龙脑
    - 龙眼
    - 归尾
    - 田螺
    - 申姜
    - 生地
    - 生姜
    - 生军
    - 仙茅
    - 及巳
    - 片苓
    - 白及
    - 白芨
    - 白求
    - 白术
    - 白芍
    - 白芷
    - 白英
    - 白矾
    - 白果
    - 白前
    - 白丑
    - 白参
    - 白苏
    - 白降
    - 白蜜
    - 白蔻
    - 白蔹
    - 白微
    - 玄参
    - 半夏
    - 地龙
    - 地黄
    - 地椒
    - 地榆
    - 地笋
    - 地锦
    - 杞子
    - 朴硝
    - 芒硝
    - 朴硝
    - 西瓜
    - 西羌
    - 列当
    - 百合
    - 百部
    - 当归
    - 当药
    - 中草
    - 曲莲
    - 肉桂
    - 肉果
    - 朱砂
    - 向前
    - 竹叶
    - 竹苓
    - 竹沥
    - 竹菇
    - 竹黄
    - 血余
    - 血蝎
    - 松节
    - 鬼刺
    - 鬼针
    - 食盐
    - 炮姜
    - 姜黄
    - 姜汁

