logging:
  level:
    root: INFO
    com.rw.random: DEBUG
spring:
  redis:
    host: 127.0.0.1
    password:
    database: 0
  r2dbc:
    url: r2dbc:mysql://localhost:3307/random_world?useSSL=false&useUnicode=true&characterEncoding=utf-8&sslMode=disabled
    username: root
    password: chiwen2233
    timeout: 10


random-world:
  objects:
    AA:
      topic: "/topic/762136123"
      heal: 1000
    GGG:
      topic: "/topic/762136123"
      heal: 1000
    MM:
      topic: "/topic/762136123"
      heal: 1000
    UUU:
      topic: "/topic/762136123"
      heal: 1000
    xxx:
      topic: "/topic/762136123"
      heal: 1000
    A:
      topic: "/topic/762136123"
      heal: 1000
    Z:
      topic: "/topic/762136123"
      heal: 1000
    999:
      topic: "/topic/762136123"
      heal: 1000
    TAT:
      topic: "/topic/762136123"
      heal: 1000
    FFF:
      topic: "/topic/762136123"
      heal: 1000

