logging:
  level:
    root: INFO
    com.rw.random: INFO
spring:
  redis:
    host: 47.110.249.236
    password: Sunlight
    database: 0
  r2dbc:
    url: r2dbc:mysql://47.110.249.236:3306/random_world?useSSL=false&useUnicode=true&characterEncoding=utf-8&sslMode=disabled
    username: root
    password: Sunlighte
    timeout: 10


random-world:
  load-test-fish-count: 500
  objects:
    AA:
      topic: "/topic/762136123"
      heal: 1000
    GGG:
      topic: "/topic/762136123"
      heal: 1000
    MM:
      topic: "/topic/762136123"
      heal: 1000
    UUU:
      topic: "/topic/762136123"
      heal: 1000
    xxx:
      topic: "/topic/762136123"
      heal: 1000
    A:
      topic: "/topic/762136123"
      heal: 1000
    Z:
      topic: "/topic/762136123"
      heal: 1000
    999:
      topic: "/topic/762136123"
      heal: 1000
    TAT:
      topic: "/topic/762136123"
      heal: 1000
    FFF:
      topic: "/topic/762136123"
      heal: 1000

